language: node_js
sudo: false
node_js:
 - '8'
cache:
  directories:
  - node_modules
script:
 - npm -v
deploy:
  provider: npm
  email: mserranom@gmail.com
  api_key:
    secure: MOSsyxitvU0Y8LogysiwV6TF4tWEkuSX954eKXXfy2HDBqHeUFSyjlHtGkeCHq2XLJ4N/67o5MfJpp0jcnONMII5CCmMStBcMMJAg7DCwZMYZCvPY548WwrhUv2D198meBiKXvHHto4QkPuxl1aubcE+2YGwrLMNzOUrlzbw24m178gKwPoV2Q09DWxY6/JOnb6n46GaEDxKBiowcfGqk8OGepDgTSQcJh8xhuUDVrv0Tse80aBCc/DE2YTT75n9yneY91hsKO5jKgjiUvggREVuKVVDigNnyDB5FsIBS+DQvzxrzPGj0PU7KYWb3+Fq71YT16MH6eEz8GsbGk/kxs9MnTqXnCj6FpZfeor0G5GeT1BiYS1ntyNpk28gMp0ryhZHWRu5fsSD9r3f4bhlMy/XsewDVgi7pkXeW8bnHEn9FdPom4TIHaddVTcJYBOZhR5I2t8vyy8NbeHqzqMJPMNQmNy7sdJ9kurbh18HV5ZV+KcwUxMLRctHv4lL+IK4W03qLLbXeGqieNRY+Tv8K3EbYyyia2BmHGn/bUT4L8qpfka4JjrCEDCAYI0471iuUxyjI/wZ6K7d6jXT1myb504XYsAEle4B0DuSPqR2bJMXL5q9QVIdZeDE/PGqY7w8qqQ/j2mADUiBaYbSKU5sfOXP29gk3rEEFWWu95cqqvs=
  on:
    repo: mserranom/bbrun
