language: node_js
sudo: false
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: npm
  email: mserranom@gmail.com
  api_key:
    secure: 1zjwLD9N5NdDe8iFRnmGKQwiZs1sx9MP7fQZjNPUrgpv4kJkVJXLp+BSB1il6C50yaqAQCmB7/tlD0nvyaERdsWunfPdVcjr6IwWK50H3iwnOHY/f0EC7JeNtPmOPoOMA99BlO/h2X+ecegii4QqDSTEBGDwg6/BzqjfEnB/HdshkoDAeKTLiRdPxPm6hEvVHphdgi9I1jMahFogUUExMpk6pAJYq+DuYAPlDVUGKYwbSXn6TiiPfruFaZblOAFo4eD4jzXu4SPnXgroj9di2h09gs3jh2wK3GkwXbfHOrPwmpC+Tddo5WUii/wBh8yJlDGNrWPDtwii7V3a9Si6mmJTrSGXnjpeLB+ih9V+in8NkMwKnJHXsiAl2dKCRoMZ5MTRcptU4LQYyg/RVfZAosLo1knD60WhGanMS6lVAmtCC28usT0MXopwGNcf/OzyTnkJAkRwN8rWX3uSIR5BE/i9u+xHezUXy0PcZ7GEIp+RlnW85E2f+UrjW4JGL8SyLIsDPvuY3VmX/7cGPn037CM5hRDdrSXLwdFycSsFaA7IkuaDSrO7/ItzJxeBWPvV6SEgkNPctnKTaMQtfjXgJYjgBwysAaIgiuLGdcESLZoKA7ATfQ3hgOPhaqepb9mlVxjPekw03ScYFAc3/R7PXgg/IJeKmQeL/wOdLwaa0h4=
  on:
    repo: mserranom/bbrun
    tags: true
