language: node_js
sudo: false
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: npm
  email: mserranom@gmail.com
  api_key:
    secure: PKLYwWqerwjeZ80z7fZ/Nq4IlavjrWeYn/yRDUnVZA74VbVfbNv6SIvMxyyfsuK3xeP3TCELmPXdh5vYtrK21SsMzw86pmOCx0HUUk1GvGGxBmICp1W/Hn9tLGNU+tWrNd414M5snHOIdt+agAuxq4/ITAk1Vv7EVBjVMuF8drBlonHqQVG0css5m8lpYC6Cyv/BIPvT7wHcBtgPan1Dp/2thwRnV9jghVSMG97ng7Qcchq3WuJcib5VDwNPTTKUVj41hp0k3z9WVAnM5TC0u1OHK6/wiadbzf0Uz6l4tibCm0nN2FcF2sZ46J59EctuYV7z6web9FADq/qqnr5q0EySEqjy9vOyLoNPXc7XParL/AR7Iv0YFv+6dNK5qkJ3nFLLgEuvEdtjU+wEDXxlfAsPMzJehs8urggf4MB0q1IYm5YNUrXqf7qPpv8bksVWL4Iv6s8HtomHYaILZZfQwnsBplTKqmYiY4wwqS5G5AnEeKDjwr9nKKmhOyhRadLWq3B9+iObKwONN+QCNQUYlTbf1YTIT61OpkqLm49QXa9qF1XSkGkaSkvY1/bEZz5TMgoPFv3yVPCNvE8T5/8h/cKDTxw1gyXeIWo2CDQXdKXf/+odBL9EcvYSR6uzTJEspNgD5Mr0zxQqRaUBP9M1gDjy+nJ32cktj0PX0N2qTpo=
  on:
    repo: mserranom/bbrun
    tags: true
